---
# file: roles/nodejs/tasks/main.yml

  - name: Add Chris Lea's PPA
    sudo: true
    apt_repository: repo='ppa:chris-lea/node.js'

  - name: Update Apt cache
    sudo: true
    apt: update_cache=yes

  - name: Install nodejs
    sudo: true
    apt: pkg=nodejs state=present
